import { render } from '@testing-library/react-native';
import App from '../App';

describe('Mobile App Performance Tests', () => {
  it('should render initial screen within 2 seconds on low-end device', async () => {
    const startTime = Date.now();
    render(<App />);
    const duration = Date.now() - startTime;
    expect(duration).toBeLessThan(2000);
  });

  it('should maintain bundle size below 15MB', async () => {
    const bundleStats = require('../dist/stats.json'); // Generated by build process
    const bundleSizeMB = bundleStats.size / (1024 * 1024);
    expect(bundleSizeMB).toBeLessThan(15);
  });

  it('should handle 1000 list items with minimal lag', async () => {
    const mockProperties = Array(1000).fill().map((_, i) => ({
      id: `prop_${i}`,
      title: `Property ${i}`,
      totalValue: 5000000,
      aiScore: 80
    }));
    const { getByTestId } = render(<PropertyList data={mockProperties} />);
    const list = getByTestId('property-list');
    const startTime = Date.now();
    fireEvent.scroll(list, { nativeEvent: { contentOffset: { y: 10000 } } });
    const duration = Date.now() - startTime;
    expect(duration).toBeLessThan(500);
  });
});