services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/sites-available/nexvestxr.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - nexvestxr-backend
      - nexvestxr-frontend
    networks:
      - nexvestxr-network

  # Backend Service
  nexvestxr-backend:
    image: nexvestxr-backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=redis://redis:6379
      - XRPL_SERVER=${XRPL_SERVER}
      - XUMM_API_KEY=${XUMM_API_KEY}
      - XUMM_API_SECRET=${XUMM_API_SECRET}
      - FLARE_RPC_URL=${FLARE_RPC_URL}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - MOONPAY_API_KEY=${MOONPAY_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - AI_SERVICE_URL=http://ai-service:5000
    volumes:
      - ./logs/backend:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - mongo
      - redis
      - ai-service
    networks:
      - nexvestxr-network

  # Frontend Service
  nexvestxr-frontend:
    image: nexvestxr-frontend:latest
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=${API_URL}
      - REACT_APP_XUMM_API_KEY=${XUMM_API_KEY}
    volumes:
      - ./logs/frontend:/var/log/nginx
    networks:
      - nexvestxr-network

  # AI Service
  ai-service:
    image: nexvestxr-ai-service:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./logs/ai-service:/app/logs
    networks:
      - nexvestxr-network

  # MongoDB
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: nexvestxr
    volumes:
      - mongo-data:/data/db
    networks:
      - nexvestxr-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - nexvestxr-network

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - nexvestxr-network

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - nexvestxr-network

volumes:
  mongo-data:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  nexvestxr-network:
    driver: bridge